In [30]:
# read image data
import cv2
def read_image(path):
    img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)
    return img

In [31]:
import json
def get_die_data(path):
    data = ""
    with open(path) as f:
        data = json.load(f)
    die_data,care_areas,exclusion_zones = data['die'],data['care_areas'],data['exclusion_zones']
    return die_data,care_areas,exclusion_zones

In [32]:
die_data,care_areas,exclusion_zones = get_die_data("/Users/shivshankar/Shiv/KLA_Hackathon/Level_1_data/input.json")
# print(img)
print(die_data)
print(care_areas)
print(exclusion_zones)

{'width': 800, 'height': 600, 'rows': 1, 'columns': 5}
[{'top_left': {'x': 0, 'y': 600}, 'bottom_right': {'x': 800, 'y': 0}}]
[]


In [33]:
img = read_image("/Users/shivshankar/Shiv/KLA_Hackathon/Level_1_data/wafer_image_1.png")
print(img.shape)

(600, 800)


In [51]:
# combine all image
import numpy as np
def combine_image():
    c = read_image("/Users/shivshankar/Shiv/KLA_Hackathon/Level_1_data/wafer_image_1.png")
    for i in range(2,6):
        img = read_image("/Users/shivshankar/Shiv/KLA_Hackathon/Level_1_data/wafer_image_"+str(i)+".png")
        c = np.concatenate((c,img),axis=1)
#     c = np.transpose(c)
    return c

In [55]:
import numpy as np
c = combine_image()
print(c.shape)
(j,i) = c.shape
dies = dict()
dies_count = 1
for ind in range(0,i,die_data['width']):
    a = c[:,ind:ind+die_data['width']]
    dies[str(dies_count)] = a
    dies_count+=1
    
for key,value in dies.items():
    print(value)

(600, 4000)
[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 159 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
